const SITE_KEY_MAP = {
  MARKET: 'MARKET',
  BEAUTY: 'BEAUTY',
} as const;

const PLUGIN_ACTION = {
  RANDOM_KURLY_PRODUCT_CARD: 'randomKurlyProductCard',
  VALIDATE_NODE_SELECTED: 'validateNodeSelected',
} as const;

const NODE_NAME_MAP = {
  PRODUCT_CARD_NODE: 'prdCard',
  PRODUCT_IMAGE_NODE: 'prdImage',
  PRODUCT_NAME_NODE: 'prdName',
} as const;

const PRODUCT_CARD_ID_MAP_KEY = 'productCardIdMap';

const INVALIDATE_NODE_TYPES = ['PAGE', 'DOCUMENT'];

const ERROR_MESSAGE_TIMEOUT = 2000;

export {
  SITE_KEY_MAP,
  PLUGIN_ACTION,
  NODE_NAME_MAP,
  PRODUCT_CARD_ID_MAP_KEY,
  INVALIDATE_NODE_TYPES,
  ERROR_MESSAGE_TIMEOUT,
};
